#:schema node_modules/wrangler/config-schema.json
name = "arroyyan"
main = "index.ts"
compatibility_date = "2025-02-20"
compatibility_flags = ["nodejs_compat"]

# Deploy to workers.dev subdomain
workers_dev = true

# Environment variables
[vars]
ENVIRONMENT = "development"
JWT_SECRET = "a162a30f3716543c7e79de09adf96ab8ca5e31920d879ba5f5bf56f3abe113cc"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "arroyyan-db"
database_id = "7e716d87-90b4-468f-933d-cf07976db393"
migrations_dir = "drizzle"
