#:schema node_modules/wrangler/config-schema.json
name = "arroyyan"
main = "src/index.ts"
compatibility_date = "2025-02-20"
compatibility_flags = ["nodejs_compat"]

# Deploy to workers.dev subdomain
workers_dev = true

# Environment variables
[vars]
ENVIRONMENT = "development"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "arroyyan-db"
database_id = "bf9bfb82-e3c6-47b3-b8c4-d6d3effc4510"
migrations_dir = "drizzle"
